/**
 * Builds a Google Slides deck of the workshop's illustrations, one slide each,
 * drawn with native shapes, text boxes and lines, so everything stays editable.
 *
 * Generated by slides/make_appscript.py from the workbench's own drawings.
 * To run it:
 *   1. Open https://script.google.com and create a new project.
 *   2. Replace the contents of Code.gs with this file.
 *   3. Services (+) → Google Slides API → Add. The script calls it to draw fast.
 *   4. Choose buildDeck in the toolbar and press Run; allow access when asked.
 *   5. The log prints the new deck's link. It is also in your Google Drive.
 */

const DECK = /*DECK*/null;

const PAGE = { w: 720, h: 405 };                        // a 16:9 slide, in points
const AREA = { x: 24, y: 54, w: 672, h: 306 };          // where a drawing goes

function buildDeck() {
  if (typeof Slides === 'undefined') {
    throw new Error('Add the Google Slides API service first: Services (+) → Google Slides API → Add.');
  }
  const deck = SlidesApp.create(DECK.title);
  const first = deck.getSlides()[0];
  const shapes = first.getShapes();
  if (shapes.length > 0) shapes[0].getText().setText(DECK.title);
  if (shapes.length > 1) shapes[1].getText().setText(DECK.subtitle);
  deck.saveAndClose();

  const id = deck.getId();
  DECK.slides.forEach(function (slide, index) {
    Slides.Presentations.batchUpdate({ requests: slideRequests(slide, index) }, id);
  });
  Logger.log('Done: ' + DECK.slides.length + ' slides. https://docs.google.com/presentation/d/' + id + '/edit');
}

// ── one slide ───────────────────────────────────────────────────────────────

function slideRequests(slide, index) {
  const page = 'figure' + index;                 // object ids need five characters or more
  let count = 0;
  const next = function () { return page + '_' + (count++); };
  const requests = [{ createSlide: { objectId: page, insertionIndex: index + 1,
                                     slideLayoutReference: { predefinedLayout: 'BLANK' } } }];

  // the heading, the step, and the caption
  const kicker = [slide.step, slide.stepTitle].filter(String).join(' · ');
  if (kicker) textBox(requests, next(), page, kicker, 24, 12, 672, 18, 9, false, false, [0.45, 0.45, 0.5], 'START');
  textBox(requests, next(), page, slide.heading, 24, 26, 672, 28, 18, true, false, [0.1, 0.1, 0.11], 'START');
  if (slide.caption) {
    textBox(requests, next(), page, slide.caption, 24, 366, 672, 32, 9, false, false, [0.45, 0.45, 0.5], 'START');
  }

  // the drawing, scaled into AREA and centred
  const view = slide.view;
  const s = Math.min(AREA.w / view[2], AREA.h / view[3]);
  const ox = AREA.x + (AREA.w - view[2] * s) / 2 - view[0] * s;
  const oy = AREA.y + (AREA.h - view[3] * s) / 2 - view[1] * s;
  const X = function (x) { return ox + x * s; };
  const Y = function (y) { return oy + y * s; };

  slide.items.forEach(function (item) {
    if (item.kind === 'text') {
      text(requests, next(), page, item, X(item.x), Y(item.y), s);
    } else if (item.kind === 'path') {
      path(requests, next, page, item, X, Y, s);
    } else {
      shape(requests, next(), page, item, X(item.x), Y(item.y), item.w * s, item.h * s, s);
    }
  });
  return requests;
}

// ── pieces ──────────────────────────────────────────────────────────────────

function pt(v) { return { magnitude: v, unit: 'PT' }; }
function rgb(c) { return { red: c[0], green: c[1], blue: c[2] }; }
function solid(c, alpha) { return { solidFill: { color: { rgbColor: rgb(c) }, alpha: alpha } }; }
function onWhite(c, alpha) { return c.map(function (v) { return v * alpha + (1 - alpha); }); }

function shape(requests, id, page, item, x, y, w, h, s) {
  const types = { rect: item.round ? 'ROUND_RECTANGLE' : 'RECTANGLE', ellipse: 'ELLIPSE',
                  diamond: 'DIAMOND', triangle: 'TRIANGLE' };
  w = Math.max(w, 0.5); h = Math.max(h, 0.5);
  const flip = item.kind === 'triangle' && item.down;
  requests.push({ createShape: { objectId: id, shapeType: types[item.kind], elementProperties: {
    pageObjectId: page, size: { width: pt(w), height: pt(h) },
    transform: { scaleX: 1, scaleY: flip ? -1 : 1, translateX: x, translateY: flip ? y + h : y, unit: 'PT' } } } });
  requests.push({ updateShapeProperties: { objectId: id, fields: 'shapeBackgroundFill,outline', shapeProperties: {
    shapeBackgroundFill: item.fill ? solid(item.fill.rgb, item.fill.alpha) : { propertyState: 'NOT_RENDERED' },
    outline: item.stroke ? { outlineFill: solid(item.stroke.rgb, item.stroke.alpha),
                             weight: pt(Math.max(item.stroke.width * s, 0.5)),
                             dashStyle: item.stroke.dash ? 'DASH' : 'SOLID' }
                         : { propertyState: 'NOT_RENDERED' } } } });
}

function text(requests, id, page, item, x, y, s) {
  const size = Math.max(item.size * s, 5);
  const w = item.text.length * size * (item.mono ? 0.62 : 0.56) + 16;
  const h = size * 1.35 + 8;
  const left = item.anchor === 'middle' ? x - w / 2 : item.anchor === 'end' ? x - w + 7.2 : x - 7.2;
  const colour = item.fill ? onWhite(item.fill.rgb, item.fill.alpha) : [0.1, 0.1, 0.11];
  const align = item.anchor === 'middle' ? 'CENTER' : item.anchor === 'end' ? 'END' : 'START';
  const room = align === 'START' ? PAGE.w - left : align === 'END' ? left + w : w;  // keep boxes on the slide
  textBox(requests, id, page, item.text, align === 'END' ? Math.max(left, 0) : left,
          y - size * 0.95 - 4, Math.min(w, Math.max(room, 40)), h, size, item.bold, item.mono, colour, align);
}

function textBox(requests, id, page, words, x, y, w, h, size, bold, mono, colour, align) {
  if (!words) return;
  requests.push({ createShape: { objectId: id, shapeType: 'TEXT_BOX', elementProperties: {
    pageObjectId: page, size: { width: pt(w), height: pt(h) },
    transform: { scaleX: 1, scaleY: 1, translateX: x, translateY: y, unit: 'PT' } } } });
  requests.push({ insertText: { objectId: id, text: words } });
  requests.push({ updateTextStyle: { objectId: id, fields: 'fontSize,bold,fontFamily,foregroundColor', style: {
    fontSize: pt(size), bold: bold, fontFamily: mono ? 'Roboto Mono' : 'Roboto',
    foregroundColor: { opaqueColor: { rgbColor: rgb(colour) } } } } });
  requests.push({ updateParagraphStyle: { objectId: id, fields: 'alignment', style: { alignment: align } } });
}

function path(requests, next, page, item, X, Y, s) {
  const pts = item.points.map(function (p) { return [X(p[0]), Y(p[1])]; });
  const segments = [];
  for (let i = 1; i < pts.length; i++) {
    const a = pts[i - 1], b = pts[i];
    if (Math.abs(b[0] - a[0]) + Math.abs(b[1] - a[1]) > 0.05) segments.push([a, b]);
  }
  const ids = [];
  segments.forEach(function (seg, i) {
    const id = next();
    ids.push(id);
    const dx = seg[1][0] - seg[0][0], dy = seg[1][1] - seg[0][1];
    requests.push({ createLine: { objectId: id, lineCategory: 'STRAIGHT', elementProperties: {
      pageObjectId: page, size: { width: pt(Math.max(Math.abs(dx), 0.1)), height: pt(Math.max(Math.abs(dy), 0.1)) },
      transform: { scaleX: dx < 0 ? -1 : 1, scaleY: dy < 0 ? -1 : 1,
                   translateX: seg[0][0], translateY: seg[0][1], unit: 'PT' } } } });
    requests.push({ updateLineProperties: { objectId: id, fields: 'lineFill,weight,dashStyle,endArrow',
      lineProperties: { lineFill: solid(item.stroke.rgb, item.stroke.alpha),
                        weight: pt(Math.max(item.stroke.width * s, 0.75)),
                        dashStyle: item.stroke.dash ? 'DASH' : 'SOLID',
                        endArrow: item.arrow && i === segments.length - 1 ? 'FILL_ARROW' : 'NONE' } } });
  });
  if (ids.length > 1) requests.push({ groupObjects: { groupObjectId: next(), childrenObjectIds: ids } });
}
